(function(g){var window=this;var qAa=function(a,b,c,d){c=(0,g.A)(c,d||a.A);b=g.oH(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},rAa=function(a){a.o||(a.o=new g.vE,g.L(a,a.o));
return a.o},i2=function(a){a.U("cardstatechange",a.ce()&&a.se()?1:0)},vAa=function(a){var b=g.bi(a,"fontSize");
var c=(c=b.match(sAa))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.de){if(String(c)in tAa)return g.ti(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in uAa)return a=a.parentNode,c=g.bi(a,"fontSize"),g.ti(a,b==c?"1em":b,"left","pixelLeft")}c=g.ie("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.qe(c);return b},j2=function(a,b){this.start=a<b?a:b;
this.end=a<b?b:a},wAa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Al&&a.dataset){if(g.qc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Ec("pollChoiceIndex"))},m2=function(a){a=g.Ma(a);
delete k2[a];g.dc(k2)&&l2&&l2.stop()},yAa=function(){l2||(l2=new g.V(function(){xAa()},20));
var a=l2;a.isActive()||a.start()},xAa=function(){var a=(0,g.H)();
g.Nb(k2,function(b){zAa(b,a)});
g.dc(k2)||yAa()},AAa=function(a,b){g.Qf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.o},n2=function(a,b,c,d){g.Yu.call(this);
if(!g.Ha(a)||!g.Ha(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.G=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.F=0;this.B=null},zAa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.B);a.B=b;BAa(a,a.progress);1==a.progress?(a.o=0,m2(a),a.Gd(),a.In()):a.sb()&&a.Rw()},BAa=function(a,b){g.Ja(a.D)&&(b=a.D(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.G[c]-a.A[c])*b+a.A[c]},o2=function(a,b,c,d,e){n2.call(this,b,c,d,e);
this.element=a},p2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
o2.call(this,a,b,c,d,e)},CAa=function(a){return Math.pow(a,3)},DAa=function(a){return 3*a*a-2*a*a*a},q2=function(a,b){(0,g.C)(b,function(c){g.gI("visualElementShown",{csn:a,
ve:g.pI(c),eventType:4},g.lI,void 0,void 0)})},r2=function(a,b){(0,g.C)(b,function(c){g.gI("visualElementHidden",{csn:a,
ve:g.pI(c),eventType:8},g.lI,void 0,void 0)})},s2=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Id=b.session_data||{};this.C=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.A={PM:a.impression,click:a.click,close:a.close,ZV:a.teaser_impression,ey:a.teaser_click};b=b.tracking_params||{};this.F=g.oI(b.card);this.H=g.oI(b.teaser);this.D=g.oI(b.icon)},t2=function(a,b){g.rg.call(this);
this.Lm=a;this.Mu=b;this[g.Vf]=!1},x2=function(a,b,c,d){t2.call(this,a,b);
a=this.Mu;b=this.ra();c?(b.setAttribute("stroke",c.o),b.setAttribute("stroke-opacity",1),c=c.ab(),g.v(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/EAa(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Mu;a=this.ra();if(d instanceof u2)a.setAttribute("fill",d.J),a.setAttribute("fill-opacity",d.K);else if(d instanceof v2){b="lg-"+d.D+"-"+d.G+"-"+d.F+"-"+d.H+"-"+d.o+"-"+d.A;var e=b in c.A?c.A[b]:null;if(!e){e=w2(c,"linearGradient",{x1:d.D,
y1:d.G,x2:d.F,y2:d.H,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.o;g.Da(d.C)&&(f+=";stop-opacity:"+d.C);f=w2(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.A;g.Da(d.B)&&(f+=";stop-opacity:"+d.B);d=w2(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=FAa(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},GAa=function(){},HAa=function(a,b){t2.call(this,a,b)},y2=function(){this.ub=[];
this.Pa=[];this.Ie=[]},z2=function(a,b,c,d){var e=a.fe[0]-b*Math.cos(g.Nd(d))+b*Math.cos(g.Nd(d+90)),f=a.fe[1]-c*Math.sin(g.Nd(d))+c*Math.sin(g.Nd(d+90));
a.ub.push(3);a.Pa.push(1);a.Ie.push(b,c,d,90,e,f);a.ao=!1;a.fe=[e,f]},JAa=function(a,b){for(var c=a.Ie,d=0,e=0,f=a.ub.length;e<f;e++){var k=a.ub[e],l=IAa[k]*a.Pa[e];
b(k,c.slice(d,d+l));d+=l}},KAa=function(a,b,c,d){x2.call(this,a,b,c,d)},A2=function(a,b){this.A=a;
this.o=b},B2=function(a,b,c,d,e){g.ww.call(this,e);
this.width=a;this.height=b;this.B=c||null;this.M=d||null},EAa=function(a){var b=a.ak();
return b?b.width/(a.B?new g.Qd(a.B,a.M):a.ak()).width:0},LAa=function(a,b){t2.call(this,a,b)},v2=function(a,b,c,d,e,f,k,l){this.D=a;
this.G=b;this.F=c;this.H=d;this.o=e;this.A=f;this.C=g.Ba(k)?k:null;this.B=g.Ba(l)?l:null},u2=function(a,b){this.J=a;
this.K=null==b?1:b},C2=function(a,b){t2.call(this,a,b)},MAa=function(a,b,c,d){x2.call(this,a,b,c,d)},D2=function(a,b){t2.call(this,a,b)},E2=function(a,b,c,d,e){B2.call(this,a,b,c,d,e);
this.A={};this.V=g.fe&&!g.Mc(526);this.K=new g.jo(this)},w2=function(a,b,c){a=a.J.o.createElementNS("http://www.w3.org/2000/svg",b);
c&&F2(a,c);return a},F2=function(a,b){for(var c in b)a.setAttribute(c,b[c])},G2=function(a,b,c,d){b=w2(a,"path",{d:NAa(b)});
c=new MAa(b,a,c,d);a.C.ra().appendChild(c.ra())},NAa=function(a){var b=[];
JAa(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},FAa=function(a,b,c){if(b in a.A)return a.A[b];
var d="_svgdef_"+OAa++;c.setAttribute("id",d);a.A[b]=d;a.H.appendChild(c);return d},PAa=function(){H2||(H2=new g.bh(400),H2.start());
return H2},I2=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.J)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.J)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.oI(a.trackingParams));var k=(0,g.J)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},q=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=q;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.dB=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.J)(u.loggingUrls||[],c);p.Ho=g.Xb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.J)(n.impressionUrls||[],c);p.cM=(0,g.J)(n.hovercardShowUrls||[],c);p.Id={itct:n.trackingParams};p.visualElement=g.oI(n.trackingParams);if("VIDEO"==q)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.bq=!1,p.Sr=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==q)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.bq=!1,p.Sr=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==q){if(q=g.Xb(u,"browseEndpoint","browseId"))p.channelId=q,p.targetUrl="/channel/"+q;p.bq=!1;p.Sr="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(q=n.hovercardButton)if(q=q.subscribeButtonRenderer){u=d(q.unsubscribedButtonText);var w=d(q.subscribedButtonText);if(q.subscribed){var D=d(q.subscriberCountWithUnsubscribeText);var F=d(q.subscriberCountText)}else D=d(q.subscriberCountText),
F=d(q.subscriberCountWithSubscribeText);var I=null;if(n.signinEndpoint&&(I=g.Xb(n,"signinEndpoint","webNavigationEndpointData","url"),!I)){n=void 0;break a}if(u&&(w||I)){n={subscribed:q.subscribed,subscribeText:u,subscribeCount:D,unsubscribeText:w,unsubscribeCount:F,enabled:q.enabled,signinUrl:I,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==q&&(p.targetUrl=g.Xb(u,"urlEndpoint","url"),p.bq=!0,p.Sr="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.re)(k,function(l){return!!l});
return f},J2=function(a){g.mV.call(this,a);
this.A=null;this.K=!1;this.B=null;this.o={};this.G={};this.F=this.C=null;this.L=[];a=g.Y(a);this.M=g.cO(a)||g.dO(a);this.xG=!0;this.H=0;this.J=new g.xq(null);this.D=new g.tH(this);g.L(this,this.D);this.D.R(this.player,g.oR("creatorendscreen"),this.MN);this.D.R(this.player,"crx_creatorendscreen",this.NN);this.D.R(this.player,"resize",this.mD);this.D.R(window,"focus",this.MU);this.load();var b=g.ke("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Nf(this,function(){g.qe(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},QAa=function(a){return a.player.getVideoData().Ic?"current":a.M?"new":"current"},K2=function(a){return"creator-endscreen-editor"===a},L2=function(a,b){g.bV(a.player,"creatorendscreen");
a.C&&(a.C.dispose(),a.C=null,a.F.dispose(),a.F=null);for(var c in a.o)a.o[c].dispose();a.o={};a.G={};0<a.L.length&&(a.L.forEach(function(l){l.dispose()}),a.L.length=0);
a.H=0;if((a.A=b)&&b.elements){RAa(a);c=[];var d=new g.mR(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.Y(a.player).A||(a.C=new g.W({I:"div",N:"ytp-ce-shadow"}),g.dV(a.player,a.C.element,4),a.F=new g.JV(a.C,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=SAa(a,e);a.o[e.id]=f;a.G[e.id]=e;g.dV(a.player,f.element,4);var k=new g.mR(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);TAa(a,f,e)}g.ZU(a.player,
c);a.mD()}},RAa=function(a){var b=g.EI(),c=g.FI();
c&&b&&a.A.visualElement&&g.qI(c,b,[a.A.visualElement],void 0)},SAa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={I:"div",da:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.Ho||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-covering-image",T:M2(b)},{I:"div",N:"ytp-ce-covering-shadow-top"},{I:"a",N:"ytp-ce-covering-overlay",T:{href:b.targetUrl,tabindex:"-1"},P:[{I:"div",da:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],T:{dir:g.yq(a.J,b.title||"")},ca:b.title},{I:"div",N:"ytp-ce-video-duration",ca:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={I:"div",da:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.Ho||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-covering-image",T:M2(b)},{I:"div",N:"ytp-ce-covering-shadow-top"},{I:"a",N:"ytp-ce-covering-overlay",T:{href:b.targetUrl,tabindex:"-1"},P:[{I:"div",da:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],T:{dir:g.yq(a.J,b.title||"")},ca:b.title},{I:"div",N:"ytp-ce-playlist-count",P:[{I:"div",
N:"ytp-ce-playlist-icon"},{I:"div",N:"ytp-ce-playlist-count-text",ca:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={I:"div",da:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.Ho||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",P:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",
P:[{I:"div",N:"ytp-ce-expanding-overlay-body",P:[{I:"div",N:"ytp-ce-expanding-overlay-body-padding",P:[{I:"a",da:["ytp-ce-channel-title","ytp-ce-link"],T:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.yq(a.J,b.title||"")},ca:b.title},b.subscribeButton?{I:"div",N:"ytp-ce-subscribe-container",P:[{I:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",N:"ytp-ce-channel-subscribers-text",ca:b.subscribersText}:"",b.metadata?{I:"div",da:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ca:b.metadata}:""]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",T:M2(b)}]};c=new g.W(c);var d=g.Xd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.T(d,"ytp-ce-subscribe-button");if(g.Y(a.player).A){var e=null;var f=b.Id.itct}else e="endscreen",f=null;e=new g.y_(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.L.push(e)}break;case "WEBSITE":c={I:"div",da:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.Ho||"","aria-hidden":"true"},P:[{I:"div",N:"ytp-ce-element-shadow"},{I:"div",N:"ytp-ce-expanding-overlay",P:[{I:"div",N:"ytp-ce-expanding-overlay-hider"},{I:"div",N:"ytp-ce-expanding-overlay-background"},{I:"div",N:"ytp-ce-expanding-overlay-content",P:[{I:"div",N:"ytp-ce-expanding-overlay-body",
P:[{I:"div",N:"ytp-ce-expanding-overlay-body-padding",P:[{I:"div",N:"ytp-ce-website-title",T:{dir:g.yq(a.J,b.title||"")},ca:b.title},{I:"div",N:"ytp-ce-website-metadata",ca:b.metadata},{I:"a",da:["ytp-ce-website-goto","ytp-ce-link"],T:{href:b.targetUrl,target:"_blank",tabindex:"-1"},ca:b.callToAction}]}]}]}]},{I:"div",N:"ytp-ce-expanding-image",T:M2(b)},{I:"div",N:"ytp-ce-expanding-icon",T:UAa(b.iconUrl)}]},c=new g.W(c)}b.o&&g.T(c.element,"ytp-ce-placeholder");return c},M2=function(a){if(a.dB)var b=
a.dB.thumbnails;
return UAa(b?b[b.length-1].url:null)},UAa=function(a){return a?{style:"background-image: url("+a+")"}:{}},TAa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.X("mouseenter",(0,g.A)(a.mw,a,b,c));b.X("mouseleave",(0,g.A)(a.Zw,a,b,c));g.Y(a.player).A||b.X("click",(0,g.A)(function(l){g.T(l.element,"ytp-ce-element-hover")},a,b));
b.X("click",(0,g.A)(a.FE,a,c));b.X("keypress",(0,g.A)(a.FE,a,c));b.X("focus",(0,g.A)(function(l,m){this.mw(l,m)},a,b,c));
b.X("blur",(0,g.A)(function(l,m){this.Zw(l,m)},a,b,c));
b.X("touchstart",(0,g.A)(a.mw,a,b,c));var f=g.Zd("ytp-ce-expanding-overlay-hider",b.element);f&&b.R(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Nr(b.element,"ytp-ce-element-hover");g.Nr(b.element,"ytp-ce-force-expand")});
b.X("keydown",(0,g.A)(function(l,m){this.xG=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.A)(function(l,m,n){this.H+=n;0<this.H?(g.T(l.element,"ytp-ce-force-expand"),N2(this,m.id,!0)):(g.Nr(l.element,"ytp-ce-force-expand"),g.Nr(l.element,"ytp-ce-element-hover"),N2(this,m.id,!1))},a,b,c);
a=(0,g.A)(function(l,m){m&&(l.X("blur",function(){g.si(m)&&this.xG&&m.focus()}),l.R(m,"focus",d),l.R(m,"blur",e))},a,b);
a(g.Zd("ytp-sb-subscribe",b.element));a(g.Zd("ytp-sb-unsubscribe",b.element));b.X("focus",d);b.X("blur",e)},N2=function(a,b,c){a.C&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.U(a.o[d].element,"ytp-ce-element-shadow-show",c)},O2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||K2(g.Y(a.player).playerStyle))c&&c();else{b=VAa(a,b);var e=0,f=!1,k=new g.V(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.zG(b[a],d)}},P2=function(a,b,c){O2(a,b.clickUrls,c);
(a=g.FI())&&b.bq&&g.sI(a,b.visualElement)},VAa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(WAa(b[e],c));return d},WAa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Q2=function(a){return g.Ha(a)&&a.length?a[0]:a},R2=function(a){var b=/.+/;
return g.v(a)&&null!=b&&null!=a&&a.match(b)?a:""},S2=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},T2=function(a){return g.v(a)?a:""},U2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},V2=function(a,b){return"true"==a||"false"==a?"true"==a:b},W2=function(a,b){return g.v(a)?parseFloat(a):b},X2=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.Jd(a,b,c);if(a>=b&&a<=c)return a}return e},XAa=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.C)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},Y2=function(a,b){if(null==a)return null;
if(g.Ia(a)){var c=[];(0,g.C)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},YAa=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.Hh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},ZAa=function(a){function b(c){return(0,g.re)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},$Aa=function(a){this.externalId=a},aBa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},Z2=function(a){if(!a)return null;
var b=g.jd(T2(a.value));b=g.gd(b);if(!b)return null;var c=U2(a.target,bBa,"current");return null==c?null:new aBa(b,c,V2(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},$2=function(a){return a.value?a.value:null},cBa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},fBa=function(a){if(!a)return null;
var b=U2(a.type,dBa),c=U2(a.trigger,eBa),d=Q2(a.url);d=Z2(d?d:null);a=Q2(a.subscribeData);var e=a?a:null;e?(a=T2(e.external_user_id),e=T2(e.subscription_token),a=a&&e?new $Aa(a):null):a=null;return b?new cBa(b,c,d,a):null},gBa=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},a3=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},b3=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Al=c;this.C=d;this.t=e;this.D=f;this.F=k;this.G=l;this.B=m;this.A=n;this.o=p},iBa=function(a,b){if(!a)return null;
var c=W2(a.x,0),d=W2(a.y,0),e=W2(a.w,0),f=W2(a.h,0),k=XAa(a.t),l=W2(a.d,0),m=W2(a.px,0),n=W2(a.py,0),p=W2(a.scaleSlope,1),q=W2(a.scaleSlopeX,p);p=W2(a.scaleSlopeY,p);var u=U2(a.scaleDimension,hBa,"xy");return b(c,d,e,f,k,l,m,n,q,p,u)},c3=function(a,b){var c=jBa(b,kBa(a,new g.Lh(a.x,a.y,a.Al,a.C),b.o)),d=b.o,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.Jd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.Jd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},kBa=function(a,b,c){var d=a.F,e=a.G,f=a.o?a.o:"xy",k=gBa(c,a.B,f);
a=a3(c,a.A,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.Lh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},lBa=function(a){return a?iBa(a,function(b,c,d,e,f,k,l,m,n,p,q){return new b3(b,c,d,e,f,k,l,m,n,p,q)}):null},mBa=function(a,b){this.o=a;
this.A=b||null},jBa=function(a,b){var c=a.A?c3(a.A,new mBa(a.o)):a.o;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.Od?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Da(c)&&(d.top+=c));return d},nBa=function(a,b,c,d,e,f,k,l,m,n,p,q,u){b3.call(this,a,b,c,d,e,l,m,n,p,q,u);
this.H=f;this.J=k},oBa=function(a){if(!a)return null;
var b=W2(a.sx,0),c=W2(a.sy,0);return iBa(a,function(d,e,f,k,l,m,n,p,q,u,w){return new nBa(d,e,f,k,l,b,c,m,n,p,q,u,w)})},pBa=function(a,b,c,d,e,f,k,l,m,n,p,q,u,w){this.A=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.o=e;this.F=f;this.C=k;this.textAlign=l;this.textSize=m;this.B=n;this.padding=p;this.effects=q;this.cornerRadius=u;this.D=w},rBa=function(a){if(!a)return null;
var b=S2(a.fgColor,"#1A1A1A"),c=S2(a.bgColor,"#FFF"),d=S2(a.borderColor,"#000"),e=X2(a.borderWidth,0,5,!1,0),f=X2(a.bgAlpha,0,1,!1,.8),k=S2(a.highlightFontColor,"#F2F2F2"),l=X2(a.highlightWidth,0,5,!1,3),m=T2(a.textAlign),n=X2(a.textSize,3.3,30.1,!0,3.6107),p=T2(a.fontWeight),q=YAa(a.padding),u=ZAa(a.effects),w=X2(a.cornerRadius,0,10,!0,0);a=Q2(a.gradient);if(a=a?a:null){var D=X2(a.x1,0,100,!0,0),F=X2(a.y1,0,100,!0,0),I=X2(a.x2,0,100,!0,100),O=X2(a.y2,0,100,!0,100),na=S2(a.color1,"#FFF"),Qa=S2(a.color2,
"#000");a=new qBa(D,F,I,O,na,Qa,X2(a.opacity1,0,100,!0,100),X2(a.opacity2,0,100,!0,0))}else a=null;return new pBa(b,c,d,e,f,k,l,m,n,p,q,u,w,a)},qBa=function(a,b,c,d,e,f,k,l){this.C=a;
this.D=b;this.B=c;this.F=d;this.o=e;this.A=f;this.G=k;this.H=l},sBa=function(a,b,c,d){this.type=a;
this.A=b;this.o=c;this.C=d},uBa=function(a){if(!a)return null;
var b=U2(a.type,tBa,"rect"),c=Y2(a.rectRegion,lBa),d=Y2(a.anchoredRegion,oBa);a=Y2(a.shapelessRegion,lBa);return new sBa(b,c,d,a)},vBa=function(a){return a.A&&a.A.length?a.A[0]:a.o&&a.o.length?a.o[0]:a.C&&a.C.length?a.C[0]:null},wBa=function(a,b){this.A=a;
this.o=b},xBa=function(a,b){this.state=a;
this.ref=b},zBa=function(a){if(!a)return null;
var b=U2(a.state,yBa);a=R2(a.ref);return b?new xBa(b,a):null},ABa=function(a,b,c,d){this.o=a||[];
this.C=b||[];this.B=c;this.A=d;this.value=!1},BBa=function(a){if(!a)return null;
var b=Y2(a.condition,zBa),c=Y2(a.notCondition,zBa),d=V2(a.show_delay,!1);a=V2(a.hide_delay,!1);return b||c?new ABa(b,c,d,a):null},CBa=function(a,b,c){(0,g.C)(a.o,g.Na(b,!1),c);
(0,g.C)(a.C,g.Na(b,!0),c)},d3=function(a,b,c,d,e,f,k,l,m,n,p,q,u,w){this.id=a;
this.author=b;this.type=c;this.style=d;this.B=e;this.segment=f;this.C=k||[];this.G=l||[];this.A=m;this.F=n;this.D=p;this.data=q;this.o=u;this.itct=w},FBa=function(a){if(!a)return null;
var b=R2(a.id),c=R2(a.author),d=U2(a.type,DBa),e=U2(a.style,e3),f=T2(Q2(a.TEXT)),k=T2(a.data);k=0!=k.length?JSON.parse(k):{};var l=Q2(a.segment);var m=l?l:null;m?(R2(m.timeRelative),l=R2(m.spaceRelative),l=(m=Y2(m.movingRegion,uBa))?new wBa(l,m):null):l=null;m=Y2(a.action,fBa);var n=Y2(a.trigger,BBa),p=Q2(a.appearance);(p=rBa(p?p:null))||(p=rBa({}));var q=U2(a.coordinate_system,EBa,"video_relative"),u=V2(a.closeable,!0),w=T2(a.log_data);a=T2(a.itct);return b&&d?new d3(b,c,d,e,f,l,m,n,p,q,u,k,w,a):
null},g3=function(a){return f3(a,function(b){return"click"==b.trigger})},f3=function(a,b){return(0,g.Ik)(a.C,b,void 0)},GBa=function(a,b,c){(0,g.C)(a.C,b,c)},HBa=function(a,b){return g.Va(a.C,b,void 0)},IBa=function(a,b,c){(0,g.C)(a.G,b,c)},JBa=function(a,b){(0,g.J)(a.G,b,void 0)},h3=function(a){return(a=KBa(a))?vBa(a):null},KBa=function(a){a.segment?(a=a.segment,a=a.o.length?a.o[0]:null):a=null;
return a},LBa=function(a,b){var c=h3(a);
return c&&b?a3(b,c.A,c.o?c.o:"xy"):1},NBa=function(a,b,c){this.o={};
this.C=!1;this.D="ivTrigger:"+a;this.A=c;CBa(b,function(d,e){var f=MBa(e.state,e.ref);this.A.subscribe(f,(0,g.A)(this.B,this,f,d));this.o[f]=d},this)},MBa=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},i3=function(){this.o=!1;
this.D=this.A=null},j3=function(a,b,c){a.A?(a.A.setSize(b,c),a.A.clear()):(b=new E2(b,c,void 0,void 0,void 0),a.A=b,a.A.Lp(),a.D=g.ie("DIV"),b=a.A.ra(),a.D.appendChild(b));
return a.A},k3=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Nb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},l3=function(a,b){var c=":"+(g.vw.getInstance().o++).toString(36);
b.setAttribute("result",c);a.appendChild(b);return c},OBa=function(a,b){var c=l3(a,k3("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=l3(a,k3("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},k3("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=l3(a,k3("feComposite",{"in":c,in2:b,operator:"in"}));return l3(a,k3("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},PBa=function(a,b){var c=l3(a,k3("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=l3(a,k3("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=l3(a,k3("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=l3(a,k3("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=l3(a,k3("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=l3(a,k3("feComposite",{operator:"out","in":c,in2:d}));return l3(a,k3("feComposite",{operator:"over","in":b,in2:c}))},QBa=function(a,b){return b},RBa=function(a){var b=
k3("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.C)(a,function(d){a:{switch(d){case "bevel":d=OBa;break a;case "dropshadow":d=PBa;break a}d=QBa}c=d(b,c)});
return b},SBa=function(a){a=(0,g.re)(a,function(b){return b in m3});
g.tb(a,function(b,c){return m3[b]-m3[c]});
return a},TBa=function(a){return g.Va(a,function(b){return"dropshadow"==b})?new g.Hh(0,7,7,0):new g.Hh(0,0,0,0)},UBa=function(a,b,c){var d=new y2;
d.moveTo(a.left+b+c,a.top+c);d.Hc(a.left+a.width-b-c,a.top+c);z2(d,b,b,-90);d.Hc(a.left+a.width-c,a.top+a.height-b-c);z2(d,b,b,0);d.Hc(a.left+b+c,a.top+a.height-c);z2(d,b,b,90);d.Hc(a.left+c,a.top+b+c);z2(d,b,b,180);d.close();return d},VBa=function(a,b,c,d){var e=a.D;
e?a=new v2(e.C*b/100,e.D*c/100,e.B*b/100,e.F*c/100,e.o,e.A,e.G,e.H):(b=a.o,a=new u2(a.bgColor,d?Math.max(b,.9):b));return a},n3=function(a,b){var c=g.Mh(a);
c.expand(TBa(b));return new g.Lh(c.left,c.top,c.right-c.left,c.bottom-c.top)},WBa=function(a,b,c){if(c.length&&(b=g.Xd(document,"g",void 0,b),b.length)){var d=SBa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.A?a.A[c]:null;e?a=e:(d=RBa(d),a=0<d.childNodes.length?FAa(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},o3=function(){i3.call(this);
this.B=0},XBa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},p3=function(a){i3.apply(this,arguments)},q3=function(a){i3.apply(this,arguments)},r3=function(a){o3.apply(this,arguments)},s3=function(a,b,c,d,e){g.K.call(this);
this.o=a;this.Y=b;this.F=c;this.ea=d;this.ga=e;this.J=!1;this.Z=new g.qH(this);g.L(this,this.Z);this.V=this.D=this.G=this.M=this.A=null;this.aa=!1;this.ba=this.K=this.L=null;this.Oq=new g.um(this.wL,100,this);g.L(this,this.Oq);this.H=new g.V(this.kC,500,this);g.L(this,this.H);this.O=this.C=this.B=null},YBa=function(a,b){var c=(0,g.A)(function(d,e,f){e=f?t3(this,e,(0,g.A)(f,this)):t3(this,e);
this.Z.X(b,d,e)},a);
c("mouseover","G",a.vD);c("mouseout","F",a.Wh);c("click","D");c("touchend","D")},ZBa=function(a){if(a.o.D){if(f3(a.o,function(d){return"close"==d.type}))var b=a.A;
else a.B=g.ie("DIV","annotation-close-button"),g.M(a.B,!1),g.nF(a.B,"annotation_id",a.o.id),a.A.appendChild(a.B),b=a.B;var c=function(d){d.stopPropagation()};
a.Z.X(b,"click",t3(a,"E",c));a.Z.X(b,"touchend",t3(a,"E",c))}},t3=function(a,b,c){return(0,g.A)(function(d){if(this.ga)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.M(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.Fe(f,"annotation")){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.M(e,
!0)}}e=g.qi(d.target);d=new g.Od(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.ea.U(b,this.o)},a)},v3=function(a){if(a.A||a.C){var b=h3(a.o);
if(b){var c=u3(a);if(a.A){b=c3(b,c);var d=g.QU(a.F).getVideoContentRect();g.oi(a.A,b.width,b.height);g.di(a.A,b.left,b.top);a.M=new g.Lh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=h3(a.o))&&d?gBa(d,e.B,e.o?e.o:"xy"):1;var f=LBa(a.o,d);d=a.o.A;d.padding?d=d.padding:(d="speech"==a.o.style?1.6:.8,d=new g.Hh(d,d,d,d));d=new g.Hh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.D&&(d.right+=1.5*c.o.height/100);a.A.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+
d.left+"px";"label"==a.o.style&&a.G&&(a.G.style.padding=a.A.style.padding);d=c.o;var k=!1,l=0,m=0;var n=g.QU(a.F).getVideoContentRect();var p=g.XU(a.F);g.Nh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.o.F&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.D){f=$Ba(a,23,b,d,e);if(a.B){var q=43-f.width;0<q&&(b.left+f.left-q>n.left&&(f.left-=q),f.width+=q)}q=f;g.oi(a.D,f.width,f.height);g.di(a.D,f.left,f.top)}a.B&&
(q?b=new g.Od(q.left+q.width-23-18,a.aa?q.top+2:q.top+q.height-18-2):(q=$Ba(a,18,b,d,e),b=new g.Od(q.left,q.top),g.oi(a.B,q.width,q.height)),g.di(a.B,b));a.V=new g.Lh(a.M.left+q.left,a.M.top+q.top,q.width,q.height);a.L=a.Z.X(g.QU(a.F),"mousemove",a.CO,a)}else a.D&&(q=e/f*d.height*4.2/100,q=new g.Qd(q,q),"highlight"==a.o.type||"label"==a.o.style?(e=1.5*d.height/100,q=new g.Lh(b.width-q.width-e,b.height-q.height-e,q.width,q.height)):q=new g.Lh(b.width-q.width-3*d.height/100,(b.height-q.height)/2,q.width,
q.height),g.oi(a.D,q.width,q.height),g.di(a.D,q.left,q.top)),a.B&&(q=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.di(a.B,q&&e?new g.Od(b.width-9,-9):q?new g.Od(b.width-9,45<b.height?9:b.height-9):e?new g.Od(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.Od(45<b.width?b.width-9-18:-9,b.height-9):new g.Od(-9,45<b.height?9:b.height-9)))}a.C&&a.C.C(a.o,c);if(a.A){c=a.A;b=a.o.A;c.style.color="highlightText"==a.o.style?b.F:b.A;q=g.QU(a.F).getVideoContentRect();c.style.fontSize=
360*b.textSize*LBa(a.o,q)/100+"px";q=a.o.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==q||"highlightText"==q?"center":"left";b.B&&(c.style.fontWeight=b.B);a=a.A;c=a.style.overflow;q=(b=g.Zd("annotation-link-icon",a))?g.si(b):!1;e=(d=g.Zd("annotation-close-button",a))?g.si(d):!1;q&&g.M(b,!1);e&&g.M(d,!1);m=f="";if(n=g.Zd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>
a.offsetWidth){l=k=vAa(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.M(d,!0);q&&g.M(b,!0)}}}},$Ba=function(a,b,c,d,e){var f=0<e;
b=new g.Lh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.T(a.A,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.T(a.A,"annotation-extend-up"),a.aa=!0);return b},w3=function(a){return"label"!=a.o.style||a.C.o},u3=function(a){var b=g.QU(a.F).getVideoContentRect();
if("player_relative"==a.o.F){var c=g.QU(a.F).getPlayerSize();b=new g.Lh(-b.left,-b.top,c.width,c.height)}else b=new g.Lh(0,0,b.width,b.height);return new mBa(b,a.O?h3(a.O):null)},aCa=function(a,b){return b?new g.Lh(a.x+b.left,a.y+b.top,b.width,b.height):null},x3=function(a,b,c){g.K.call(this);
this.A=a;this.annotation=b;this.view=c;this.o=null;this.C=this.isVisible=!1;bCa(b,a)},bCa=function(a,b){JBa(a,function(c){return new NBa(a.id,c,b)})},cCa=function(a){a.A.unsubscribe("resize",a.uD,a);
a.A.unsubscribe("onVideoAreaChange",a.kF,a)},y3=function(a){a.o&&(a.o.stop(),a.o=null)},dCa=function(a,b,c){s2.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=Z2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},z3=function(a,b,c){s2.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.B=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=Z2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.o=null;if(a=b.signin_url)this.o=Z2({target:"current",value:a});this.L=b.signin_title||null;this.K=b.signin_message||null},eCa=function(a,b,c){z3.call(this,a,b,c);
this.J=b.ypc_flow_type;this.G=b.innertube_request_params},fCa=function(a,b,c){s2.call(this,a,b,c);
this.B=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=Z2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},gCa=function(a,b,c){s2.call(this,a,b,c);
this.G=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.o=b.hasOwnProperty("old_vote")?b.old_vote:null;this.B=null;if(a=b.signin_url)this.B=Z2({target:"current",value:a});this.J=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},iCa=function(a,b,c){z3.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new hCa(a[b]))},hCa=function(a){this.merchant=g.G(a.merchant);
this.price=g.G(a.price)},jCa=function(a,b,c){z3.call(this,a,b,c);
this.M=b.ypc_item_type;this.J=b.ypc_item_id;this.G=b.ypc_flow_type},kCa=function(a,b,c){s2.call(this,a,b,c);
this.B=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=Z2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},A3=function(a,b,c){s2.call(this,a,b,c);
this.J=b.image_url;this.B=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.G=!!b.is_paygated;this.K=!!b.user_has_entitlement;this.url=Z2({target:b.target||"new",value:b.url})},lCa=function(a){this.o=a;
this.A={}},mCa=function(a){var b={};
b=(b["iv-event"]=1,b);g.WU(a.o,"iv",b,void 0)},E3=function(a,b,c,d){if(b){var e=B3(a,b);
a.A[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=C3(a,"cta_annotation_shown",e,c);D3(a,e,nCa(b,d))}},F3=function(a,b,c,d,e,f){if(b){var k=B3(a,b);
k["iv-event"]=3;k["i-time"]=a.A[b]||"";d&&g.lc(k,d);b=C3(a,"cta_annotation_clicked",k,e);D3(a,k,b,c,f)}},G3=function(a,b){if(b){var c=B3(a,b);
c["iv-event"]=4;c["i-time"]=a.A[b]||"";var d=C3(a,"cta_annotation_closed",c);D3(a,c,d)}},nCa=function(a,b){return b?(0,g.J)(a,g.Na(function(c,d){return g.ro(d,c)},b)):a},C3=function(a,b,c,d){d=d?g.jb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Y(a.o).experiments.o("enable_async_click_tracking")){a:{c=c["a-id"];a=a.o.getVideoData();if(a.lA){if((b=a.lA[b])&&g.yK(b)){a=g.rc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.jr){b=g.PF(a.jr,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},D3=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.C)(c||[],function(n){f++;
g.zG(n,m)});
e&&(f++,0!=e&&a.o.sendVideoStatsEngageEvent(e,m));g.WU(a.o,"iv",b,m)},B3=function(a,b){var c={};
if(b){var d=new g.$n(b);(0,g.C)(d.Gb(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.o.getCurrentTime().toFixed(2);
c.ps=g.Y(a.o).playerStyle;return c},H3=function(a,b,c,d,e){e=B3(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;D3(a,e,d)},I3=function(a,b,c,d){c&&(c=B3(a,c),c["iv-event"]=b,D3(a,c,d))},oCa=function(a,b,c,d,e,f,k){this.A=a;
this.B=b;this.D=c;this.videoData=d;this.logger=e;this.o=f;this.C=k},J3=function(a,b,c){this.o=a;
this.B=b;this.D=c;this.A=new g.xq(null)},qCa=function(a,b){var c=[];
(0,g.C)(b.choices,function(k){c.push({I:"li",N:b.G+"-"+k.index.toString(),P:[{I:"label",P:[{I:"input",N:"iv-card-poll-choice-input",T:{type:"checkbox",role:"radio",name:b.G+k.index.toString(),value:k.index.toString(),"data-poll-choice-index":k.index.toString()}},{I:"span",N:"iv-card-poll-choice-text",P:[{I:"span",N:"iv-card-poll-choice-percent"},K3(this,"span",void 0,k.desc)]}]},{I:"div",N:"iv-card-poll-result",P:[{I:"div",N:"iv-card-poll-result-bar"}]}]})},a);
var d={I:"ul",T:{role:"radiogroup"},P:c},e={};b.B&&(e["aria-label"]=g.wV("$POLL_TITLE - Inicia sesi\u00f3n para votar.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{I:"div",N:"iv-card-content",P:[K3(a,"h2",e,b.title),{I:"form",P:[{I:"fieldset",P:[d]}]}]}];b.B&&(f.push("iv-card-unavailable"),d.push({I:"div",da:["iv-card-sign-in"],P:[{I:"h2",ca:"\u00bfTe gustar\u00eda votar?"},{I:"a",da:["iv-card-sign-in-button","iv-button"],T:{href:$2(b.B)},P:[{I:"span",da:["iv-button-content"],ca:"Iniciar sesi\u00f3n"}]}]}));
f=new g.W({I:"div",da:f,P:d});d=f.element;pCa(b,d);qAa(a.o.A,d,g.Na(a.G,b),a);(0,g.C)(g.Yd("iv-card-poll-choice-input",d),function(k){this.o.A.X(k,"focus",g.Na(this.C,!0));this.o.A.X(k,"blur",g.Na(this.C,!1))},a);
b.B&&(d=g.Zd("iv-card-sign-in-button",d),a.B(d,b.B,b.id,b.Id,b.C,b.A.click,5));return f},N3=function(a,b,c,d){var e=b.displayDomain?{I:"div",
N:"iv-card-image-text",ca:b.displayDomain}:"",f=rCa(a,b),k=["iv-card"];b.o&&k.push("iv-card-unavailable");e=[{I:"a",N:"iv-click-target",T:{href:$2(b.url)},P:[L3(b.imageUrl,e),{I:"div",N:"iv-card-content",P:[K3(a,"h2",void 0,b.title),f]}]}];b.o&&e.push({I:"div",da:["iv-card-sign-in"],P:[K3(a,"h2",void 0,b.L||""),{I:"p",ca:b.K},{I:"a",da:["iv-card-sign-in-button","iv-button"],T:{href:$2(b.o)},P:[K3(a,"span","iv-button-content","Iniciar sesi\u00f3n")]}]});k=new g.W({I:"div",da:k,P:e});M3(a,k,b,c,d);
return k},sCa=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.K?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.G&&b.B?{I:"span",da:d,T:e,ca:b.B}:"";c={I:"div",da:["iv-card",c],P:[{I:"a",N:"iv-click-target",T:{href:$2(b.url)},P:[L3(b.J,d?{I:"div",N:"iv-card-image-text",P:[d,b.priceText]}:""),{I:"div",N:"iv-card-content",P:[{I:"h2",N:"iv-card-primary-link",ca:b.title},O3(a,b)]}]}]};c=new g.W(c);M3(a,c,b);return c},P3=function(a,b){return b.customMessage?K3(a,"div",
"iv-card-message",b.customMessage):""},L3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{I:"div",N:"iv-card-image",T:{style:c},P:d}},O3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.C)(b.metaInfo,function(d){c.push(K3(this,"li","",d))},a);
return{I:"ul",N:"iv-card-meta-info",P:c}},K3=function(a,b,c,d){c?g.v(c)?c={"class":c}:g.Ha(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.yq(a.A,d);return{I:b,T:c,ca:d}},rCa=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.B&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.B+");");d.dir=g.yq(a.A,b.customMessage);var e=[{I:"span",ca:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({I:"span",N:"iv-card-link-icon"}));return{I:"div",da:c,T:d,P:e}},pCa=function(a,b){var c=0;
(0,g.C)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Zd(a.G+"-"+e.index.toString(),b);e=e.count/c;null==a.o&&(e=0);g.U(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.o==d);f.getElementsByTagName("input")[0].checked=a.o==d;var k=Math.floor(100*e).toFixed(0),l=g.Zd("iv-card-poll-choice-percent",f);g.ye(l,g.wV("$PERCENT%",{PERCENT:k}));f=g.Zd("iv-card-poll-result-bar",f);g.Xh(f,"transform","scaleX("+e.toFixed(2)+")")}g.U(b,"iv-card-poll-voted",null!=a.o);g.U(b,"iv-card-poll-expanded",
null!=a.o&&1<a.choices.length)},tCa=function(a,b,c,d){d?(c&&a.o.videoData.Da||a.o.o.pauseVideo(),a.o.o.isFullscreen()&&a.o.o.toggleFullscreen(),F3(a.o.logger,b.C,d,void 0,b.A.click,5),(a=g.FI())&&g.sI(a,b.F)):b.url&&a.D(b.url,b.id,b.Id,b.C,b.A.click||[],5)},M3=function(a,b,c,d,e){c.o&&uCa(a,g.Yd("iv-card-sign-in-button",b.element),c,c.o,e);
c.url&&uCa(a,g.Yd("iv-click-target",b.element),c,c.url,d)},uCa=function(a,b,c,d,e){(0,g.C)(b,function(f){if(e){var k=(0,g.A)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.o.A.X(f,"click",k)}else d&&this.B(f,d,c.id,c.Id,c.C,c.A.click,5)},a)},vCa=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},Q3=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=wCa(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},wCa=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},xCa=function(a){a=$2(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!Q3(a))||(b=g.oh(g.nh(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.NF(a);if(!b||!b.v)return null;if(b=b.t)return vCa(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.LF(a[1]))&&a.t?vCa(a.t):-1},yCa=function(a){a=$2(a);
a=a.replace(/https?:\/\//g,"");return Q3(a)?(a=g.NF(a))&&a.v?a.v:null:null},zCa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},R3=function(a,b){return b?b:Q3(a)?"current":"new"},S3=function(a,b){g.K.call(this);
this.Fa=a;this.context=b;this.Ky=!1;this.ea=0},ACa=function(a){return(0,g.H)()-a.ea},BCa=function(a,b,c,d,e,f){var k=$2(b);
if(k){var l=R3(k,b.target),m=(0,g.A)(function(){b.o&&this.context.o.pauseVideo();var p=this.context.videoData.Ic||!1,q=g.NF(k||"");p&&q&&(q.v||q.list)?g.M0(this.context.o.app,q.v,c,q.list,!1,void 0,void 0):g.uV(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=ACa(a);F3(a.context.logger,d,m,n,e,f);Q3(k)||(a=g.FI(),d=c.itct,a&&d&&g.sI(a,g.oI(d)))}},V3=function(a,b,c){S3.call(this,b,c);
var d=this;this.A=a;this.Y=null;this.aa=this.ya=this.D=this.xa=!1;this.ba=null;this.V=new g.V(g.z,c.D.sd?4E3:3E3);g.L(this,this.V);this.ma=new g.V(g.z);g.L(this,this.ma);this.F=new J3(c,(0,g.A)(this.ll,this),(0,g.A)(this.lq,this));this.J=new g.W({I:"div",N:"iv-drawer",T:{id:"iv-drawer"},P:[{I:"div",N:"iv-drawer-header",T:{"aria-role":"heading"},P:[{I:"span",N:"iv-drawer-header-text"},{I:"button",da:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{I:"div",
N:"iv-drawer-content"}]});g.L(this,this.J);this.G=this.J.element;this.ha=new g.JV(this.J,330);g.L(this,this.ha);this.Aa=g.Zd("iv-drawer-header-text",this.G);this.B=g.Zd("iv-drawer-content",this.G);this.C=[];this.sa=this.O=this.H=this.ga=this.o=null;this.L=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.ya&&T3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.ya=d.D)&&U3(d)});
this.M=this.K=this.ia=null},HCa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&CCa[c]){c=new CCa[c](b.id,b.data,b.o);if(!a.xa){g.Mr(a.ra(),["html5-stop-propagation","iv-drawer-manager"]);g.dV(a.A,a.G,5);DCa(a);a.O=g.Zd("ytp-cards-button",a.A.getRootNode());var d=g.Zd("iv-drawer-close-button",a.G);a.sa=d;a.xa=!0}ECa(a,c.id);var e=FCa(a,c);if(e){d={jc:c,Tt:e.element,UC:!1};var f=GCa(a,d);g.nb(a.C,f,0,d);e.A(a.B,f);a.To();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Na(a.HV,d)):(e=1E3*a.context.o.getCurrentTime(),5E3>e&&e>c.startMs&&a.cG(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Na(a.cG,d)),W3(a))}}},ICa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){T3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){U3(a)});
var c=b.data.headerText;g.ye(a.Aa,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.Y=b.data.eventId);a.ia=g.oI(b.data.trackingParams);a.M=g.oI(b.data.closeTrackingParams);a.K=g.oI(b.data.iconTrackingParams)},ECa=function(a,b){var c=JCa(a,b);
c&&(c==a.o&&(a.o=null),a.A.removeCueRange(c.jc.id),g.qe(c.Tt),g.eb(a.C,c),a.To(),W3(a))},T3=function(a,b,c,d){if(!a.D){a.ha.show();
a.ga=new g.V(function(){g.T(a.context.o.getRootNode(),"ytp-iv-drawer-open")},0);
a.ga.start();a.ba=g.fH(a.B,"mousewheel",(0,g.A)(a.eO,a));a.D=!0;a.ea=(0,g.H)();H3(a.context.logger,a.Y,7,void 0,d&&d.jc?d.jc.C:void 0);var e=g.FI();e&&a.ia&&a.M&&q2(e,[a.ia,a.M]);var f={TRIGGER_TYPE:b};(0,g.C)(a.C,function(k){k.UC||(k.UC=!0,E3(a.context.logger,k.jc.C,k.jc.A.PM,f));e&&q2(e,[k.jc.F])});
i2(a.A);c&&(a.H=new g.V(function(){a.ka=a.O;a.sa.focus()},330),a.H.start())}},U3=function(a){a.D&&(a.ha.hide(),g.gH(a.ba),a.ba=null,g.Nr(a.context.o.getRootNode(),"ytp-iv-drawer-open"),a.D=!1,i2(a.A),a.H&&a.H.stop(),a.H=new g.V(function(){a.ka&&(a.ka.focus(),a.ka=null)},330),a.H.start())},DCa=function(a){var b=g.Zd("iv-drawer-close-button",a.G);
a.context.A.X(b,"click",a.lK,a);a.context.A.X(a.B,"touchend",function(){a.V.start()});
a.context.A.X(a.B,"scroll",a.xK,a);a.context.C.subscribe("onHideControls",function(){a.aa=!0});
a.context.C.subscribe("onShowControls",function(){a.aa=!1});
a.context.C.subscribe("onVideoAreaChange",function(){a.aa=g.Lr(a.A.getRootNode(),"ytp-autohide")});
a.L.push(g.xF("iv-button-shown",a.lN,a));a.L.push(g.xF("iv-button-hidden",a.kN,a));a.L.push(g.xF("iv-teaser-shown",a.oN,a));a.L.push(g.xF("iv-teaser-hidden",a.nN,a));a.L.push(g.xF("iv-teaser-clicked",a.mN,a))},FCa=function(a,b){switch(b.type){case "simple":return N3(a.F,b);
case "collaborator":var c=a.F,d={I:"div",da:["iv-card","iv-card-channel"],P:[{I:"a",da:["iv-click-target"],T:{href:$2(b.url),"data-ytid":b.channelId},P:[L3(b.profileImageUrl),{I:"div",N:"iv-card-content",P:[P3(c,b),{I:"h2",N:"iv-card-primary-link",ca:b.title},O3(c,b)]}]}]};d=new g.W(d);M3(c,d,b);return d;case "donation":return c=a.F,d=(0,g.A)(c.F,c,b),N3(c,b,d,d);case "episode":return sCa(a.F,b,"iv-card-episode");case "movie":return sCa(a.F,b,"iv-card-movie");case "playlist":return c=a.F,d={I:"div",
da:["iv-card","iv-card-playlist"],P:[{I:"a",N:"iv-click-target",T:{href:$2(b.url)},P:[L3(b.B,{I:"div",N:"iv-card-image-overlay",P:[{I:"span",N:"iv-card-playlist-video-count",ca:b.playlistVideoCount.toString()}]}),{I:"div",N:"iv-card-content",P:[P3(c,b),K3(c,"h2","iv-card-primary-link",b.title),O3(c,b)]}]}]},d=new g.W(d),M3(c,d,b),d;case "poll":return qCa(a.F,b);case "productListing":c=a.F;var e=!g.ab(b.offers);d=["iv-card"];var f="",k=rCa(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",
e=b.offers[0],k=[],e.price&&k.push({I:"div",N:"iv-card-offer-price",ca:e.price}),e.merchant&&k.push({I:"div",N:"iv-card-offer-merchant",ca:e.merchant}),k={I:"div",P:k});d={I:"div",da:d,T:{tabindex:"0"},P:[{I:"a",da:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+b.imageUrl+");",href:$2(b.url),"aria-hidden":"true",tabindex:"-1"}},{I:"div",N:"iv-card-content",P:[b.sponsored?{I:"div",N:"iv-card-sponsored",P:["Patrocinado",{I:"div",N:"iv-ad-info-container",P:[{I:"div",N:"iv-ad-info",
ca:"{{adInfo}}"},{I:"div",N:"iv-ad-info-icon-container",P:[{I:"div",N:"iv-ad-info-icon"},{I:"div",N:"iv-ad-info-callout"}]}]}]}:"",{I:"a",N:"iv-click-target",T:{href:$2(b.url)},P:[K3(c,"h2",f,b.title),k]}]}]};d=new g.W(d);f=g.ke("span");g.ye(f,"Est\u00e1s viendo este producto porque creemos que es relevante para el v\u00eddeo. Es posible que Google reciba una compensaci\u00f3n de parte del comerciante.");d.Kb(f,"adInfo");M3(c,d,b);return d;case "tip":return c=a.F,d=(0,g.A)(c.H,c,b),N3(c,b,d,d);case "video":return c=
a.F,d=b.isLiveNow?{I:"span",da:["yt-badge","yt-badge-live"],ca:"EN DIRECTO AHORA"}:"",d={I:"div",da:["iv-card","iv-card-video"],P:[{I:"a",N:"iv-click-target",T:{href:$2(b.url)},P:[L3(b.B,b.videoDuration?{I:"span",N:"iv-card-video-duration",ca:b.videoDuration}:""),{I:"div",N:"iv-card-content",P:[P3(c,b),K3(c,"h2","iv-card-primary-link",b.title),O3(c,b),d]}]}]},d=new g.W(d),M3(c,d,b),d}return null},GCa=function(a,b){if(0==a.C.length)return 0;
var c=g.Wa(a.C,function(d){return b.jc.startMs>d.jc.startMs||b.jc.startMs==d.jc.startMs&&b.jc.timestamp>=d.jc.timestamp?!0:!1});
return-1==c?0:c+1},KCa=function(a){return a.o?"productListing"==a.o.jc.type:(0,g.Fj)(a.C,function(b){return"productListing"==b.jc.type})},W3=function(a){g.U(a.A.getRootNode(),"ytp-cards-shopping-active",KCa(a))},LCa=function(a,b){if(a.J.C){var c=new n2([0,
a.B.scrollTop],[0,b.Tt.offsetTop],600,DAa);a.context.B.X(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.B.X(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.lQ(a.J,!0),a.B.scrollTop=b.Tt.offsetTop,g.lQ(a.J,!1)},X3=function(a){return a.o&&a.o.jc?a.o.jc:a.C[0]&&a.C[0].jc?a.C[0].jc:null},JCa=function(a,b){return g.Va(a.C,function(c){return c.jc.id==b})},Y3=function(a,b,c){S3.call(this,a,b);
this.annotation=c;this.isActive=!1},MCa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},Z3=function(a,b,c){Y3.call(this,a,b,c);
this.A=null;this.G=!1;this.C=null;this.B=!1;this.H=0;this.o=this.F=this.D=null},$3=function(a,b,c){Y3.call(this,a,b,c);
this.J=this.D=this.K=!1;this.G=5E3;this.B=null;this.H=g.ie("DIV","iv-promo-contents");this.A=this.C=this.o=null;this.F=new g.V(function(){this.o.setAttribute("aria-hidden",!0);g.M(this.C,!1);g.M(this.A,!0)},700,this);
g.L(this,this.F)},NCa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.ra().setAttribute("aria-hidden",!0);a.ra().setAttribute("aria-label","Promoci\u00f3n");a.ra().tabIndex=0;var e=a.annotation.Xa(),f=b.image_url;if(f){var k=g.ie("DIV",["iv-promo-img","iv-click-target"]);f=g.ie("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.ie("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.ie("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.ll(k,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}e?(f=g.ie("A","iv-promo-txt"),g.Fd(f,$2(e)),a.o=f):a.o=g.ie("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.ie("P",null,g.ie("STRONG",null,b.text_line_1));var m=g.ie("P",null,g.ie("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
a.context.D.experiments.o("web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.ie("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.ie("BUTTON",["iv-button","iv-promo-button"],g.ie("SPAN","iv-button-content",f));var p=g.ie("DIV","iv-promo-button-container");p.appendChild(f);e&&a.ll(a.ra(),e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}g.T(a.o,"iv-click-target");e&&a.ll(a.o,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c);break;case "playlist":case "video":l=
g.ie("P",null,g.ie("SPAN",null,b.text_line_1)),m=g.ie("P",null,g.ie("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.ie("SPAN",["yt-badge","iv-promo-badge-live"],"EN DIRECTO AHORA")),g.T(a.o,"iv-click-target"),e&&a.ll(a.o,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);p&&a.H.appendChild(p);c=g.ie("DIV","iv-promo-actions");a.A=g.ie("BUTTON",["iv-promo-expand","ytp-button"]);a.A.title="Expandir";a.context.A.X(a.A,
"click",g.Na(a.Ru,5E3),a);c.appendChild(a.A);g.M(a.A,!1);a.context.A.X(a.ra(),"mouseover",a.yL,a);a.context.A.X(a.ra(),"mouseout",a.xL,a);a.context.A.X(a.ra(),"touchend",g.Na(a.Ru,5E3),a);a.C=g.ie("BUTTON",["iv-promo-close","ytp-button"]);a.C.title="Cerrar";a.context.A.X(a.C,"click","cta"==a.annotation.style&&b.text_line_3?a.nL:a.DO,a);c.appendChild(a.C);g.Mr(a.ra(),d);k&&(a.ra().appendChild(k),n&&k.appendChild(n));a.ra().appendChild(a.H);a.ra().appendChild(c)},OCa=function(a){a.D||a.J||a.B||(g.T(a.ra(),
"iv-promo-collapsed"),a.D=!0,a.F.start())},PCa=function(a){a.F.stop();
a.D&&(g.Or(a.ra(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.D=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.M(a.A,!1),g.M(a.C,!0))},QCa=function(a,b){a.B||(a.B=g.ch(function(){a4(this);
OCa(this)},b,a))},a4=function(a){a.B&&(g.dh(a.B),a.B=null)},b4=function(a){g.mV.call(this,a);
this.K=!1;this.J=0;this.A={};this.L={};this.jb=new lCa(a);this.G=new g.tH(this);g.L(this,this.G);this.F=this.C=null;this.G.R(this.player,"onVideoAreaChange",(0,g.A)(this.U,this,"onVideoAreaChange"));this.G.R(this.player,"onHideControls",(0,g.A)(this.U,this,"onHideControls"));this.G.R(this.player,"onShowControls",(0,g.A)(this.U,this,"onShowControls"));this.G.R(this.player,"resize",(0,g.A)(this.U,this,"resize"));this.G.R(this.player,"presentingplayerstatechange",(0,g.A)(this.U,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.JR,this);this.subscribe("onShowControls",this.RT,this);this.subscribe("presentingplayerstatechange",this.XS,this);this.subscribe("resize",this.ax,this);this.subscribe("G",this.KN,this);this.subscribe("F",this.Wh,this);this.subscribe("D",this.sQ,this);this.subscribe("E",this.YQ,this);g.Y(this.player).J.subscribe("vast_info_card_add",this.jF,this);this.O=new g.tH(this);g.L(this,this.O);this.O.R(this.player,g.oR("annotations_module"),this.IN);this.O.R(this.player,
"crx_annotations_module",this.JN);this.V=g.ie("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.Y=g.ie("DIV","video-custom-annotations");this.D=new g.W({I:"div",da:["ytp-player-content","ytp-iv-player-content"]});g.L(this,this.D);g.dV(this.player,this.D.element,4);this.D.hide();this.B=new g.W({I:"div",da:["ytp-iv-video-content"]});g.L(this,this.B);g.me(this.B.element,g.ie("DIV","video-annotations",this.V,this.Y));this.H=this.o=null;this.M=[];RCa(this)&&this.load();var b=g.ke("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Nf(this,function(){g.qe(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},SCa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},RCa=function(a){var b=g.Y(a.player);
a=a.player.getVideoData();return 1==(b.kh||a.kh)&&!a.Bl||null!==b.J.get(a.videoId)},TCa=function(a,b,c){a.K=!0;
a.F=g.eG(b,c)},UCa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(UCa(a,e))}return c},VCa=function(a,b,c){return!(a.loaded&&a.J==b&&a.player.getVideoData().videoId==
c)},XCa=function(a,b){var c=WCa(a,b);
if(!c&&"marker"!=b.type)return null;IBa(b,function(e){e=(0,g.A)(this.sU,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new x3(a.ha,b,c);g.L(d,c);return d},YCa=function(a,b){var c=g.ie("DIV",["annotation",
"annotation-type-custom"]);g.M(c,!1);var d=null;switch(b.type){case "branding":if(g.Y(a.player).ed)break;a.D.element.appendChild(c);d=new Z3(c,c4(a),b);break;case "promotion":g.dV(a.player,c,4),d=new $3(c,c4(a),b)}d&&d.Kr();return d},aDa=function(a){var b=a.player.getVideoData();
if(b.re){var c=g.Y(a.player),d=c.J.get(b.videoId);if(d){var e={format:"XML",ad:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.ad.gaming="1");e.Gd=(0,g.A)(function(f,k,l){VCa(this,f,k)||(f=g.ZF(l)&&l.responseXML?l.responseXML:null)&&d4(this,f)},a,a.J,b.videoId);
g.ZH()&&(e.Gd=ZCa(a,e.Gd));e.Rb={ic_only:"1"};$Ca(e,d);a.K=!0;g.eG(b.re,e)}}},$Ca=function(a,b){a.method="POST";
a.Rb=a.Rb||{};b.St&&(a.Rb.ic_coll=b.St);b.ri&&(a.Rb.ic_xml=b.ri);b.tl&&(a.Rb.ic_track=b.tl)},bDa=function(a){var b=new g.W({I:"div"});
g.M(b.element,!1);var c=new V3(a.player,b.element,c4(a));g.L(c,b);b.A(a.D.element);c.Kr();return c},c4=function(a){if(!a.H){var b=new g.qH(a);
g.L(a,b);var c=new g.jo(a);g.L(a,c);a.H=new oCa(b,c,g.Y(a.player),a.player.getVideoData(),a.jb,a.player,a.ha)}return a.H},d4=function(a,b){var c=!1;
cDa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=UCa(a,d[e]),k=null;try{k=FBa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=YCa(a,k))g.L(a,f),a.L[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.o||(a.o=bDa(a),g.L(a,a.o)),"card"==k.type?HCa(a.o,k):ICa(a.o,k),c=!0;else if(f=XCa(a,k))g.L(a,f),a.A[k.id]=f}}c&&(i2(a.player),a.ax());g.Nb(a.A,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.A&&
(m=this.A[m.segment.A])&&(l.O=m.annotation)}},a)},cDa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.FI();
if(b){var c=g.EI();c&&g.qI(b,c,[g.oI(a)])}}},eDa=function(a,b,c,d){d?dDa(a,b,c):e4(a,b,c)},e4=function(a,b,c){if(b=a.A[b])y3(b),c&&c.A?(a=(0,g.A)(a.jC,a,b),b.o=new g.V(a,2E3),b.o.start()):a.jC(b)},dDa=function(a,b,c){if(b=a.A[b])y3(b),c&&c.B?(a=(0,g.A)(a.oG,a,b),b.o=new g.V(a,2E3),b.o.start()):a.oG(b)},fDa=function(a,b){var c=a.player.getVideoData();
if(!c.No)return!1;var d=$2(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!Q3(d))return!1;d=g.NF(d);return d.list||d.p?!1:(d=yCa(b))?c.videoId==d?!0:"new"!=b.target&&g.Y(a.player).o?!0:!1:!1},WCa=function(a,b){if(gDa(b)){var c=b.D||f3(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new s3(b,(0,g.A)(a.V.appendChild,a.V),a.player,a.ha,c)}return null},gDa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in e3)if(a.style==e3[b])return!0;return!1},f4=function(a,b,c,d){a.U(MBa(b,d),c,d)},ZCa=function(a,b){return(0,g.A)(function(){if(!this.la()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Na.apply(window,c);this.M.push(g.XH(b))}},a)};
g.LU.prototype.il=g.ca(13,function(a,b){var c=g.MU(this).B;c&&c.il(a,b)});
var sAa=/[^\d]+$/,tAa={cm:1,"in":1,mm:1,pc:1,pt:1},uAa={em:1,ex:1};j2.prototype.clone=function(){return new j2(this.start,this.end)};
j2.prototype.getLength=function(){return this.end-this.start};
var k2={},l2=null;g.B(AAa,g.Qf);g.B(n2,g.Yu);g.h=n2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.sb())return!1;m2(this);this.startTime=a=(0,g.H)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Qq();this.Ke("play");-1==this.o&&this.Ke("resume");this.o=1;var b=g.Ma(this);b in k2||(k2[b]=this);yAa();zAa(this,a);return!0};
g.h.stop=function(a){m2(this);this.o=0;a&&(this.progress=1);BAa(this,this.progress);this.Ke("stop");this.In()};
g.h.pause=function(){this.sb()&&(m2(this),this.o=-1,this.Ke("pause"))};
g.h.W=function(){0==this.o||this.stop(!1);this.Ke("destroy");n2.fa.W.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Rw=function(){this.Ke("animate")};
g.h.Ke=function(a){this.dispatchEvent(new AAa(a,this))};
g.B(o2,n2);o2.prototype.C=g.z;o2.prototype.Rw=function(){this.C();o2.fa.Rw.call(this)};
o2.prototype.In=function(){this.C();o2.fa.In.call(this)};
o2.prototype.Qq=function(){this.C();o2.fa.Qq.call(this)};
g.B(p2,o2);p2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.B(t2,g.rg);g.h=t2.prototype;g.h.Mu=null;g.h.Lm=null;g.h.ra=function(){return this.Lm};
g.h.addEventListener=function(a,b,c,d){g.dg(this.Lm,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.lg(this.Lm,a,b,c,d)};
g.h.W=function(){t2.fa.W.call(this);var a=this.Lm;if(a)if(g.Wf(a))a.Le&&g.$f(a.Le);else if(a=g.gg(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.mg(d[e])&&++b}};g.B(x2,t2);x2.prototype.fill=null;g.B(HAa,t2);y2.prototype.Nf=null;y2.prototype.fe=null;y2.prototype.ao=!0;var IAa=[2,2,6,6,0];g.h=y2.prototype;g.h.clear=function(){this.ub.length=0;this.Pa.length=0;this.Ie.length=0;delete this.Nf;delete this.fe;delete this.ao;return this};
g.h.moveTo=function(a,b){0==g.Sa(this.ub)?this.Ie.length-=2:(this.ub.push(0),this.Pa.push(1));this.Ie.push(a,b);this.fe=this.Nf=[a,b];return this};
g.h.Hc=function(a){var b=g.Sa(this.ub);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.ub.push(1),this.Pa.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Ie.push(c,d)}this.Pa[this.Pa.length-1]+=b/2;this.fe=[c,d]};
g.h.close=function(){var a=g.Sa(this.ub);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.ub.push(4),this.Pa.push(1),this.fe=this.Nf);return this};
g.h.clone=function(){var a=new this.constructor;a.ub=this.ub.concat();a.Pa=this.Pa.concat();a.Ie=this.Ie.concat();a.Nf=this.Nf&&this.Nf.concat();a.fe=this.fe&&this.fe.concat();a.ao=this.ao;return a};
g.h.transform=function(a){if(!this.ao)throw Error("Non-simple path");a.transform(this.Ie,0,this.Ie,0,this.Ie.length/2);this.Nf&&a.transform(this.Nf,0,this.Nf,0,1);this.fe&&this.Nf!=this.fe&&a.transform(this.fe,0,this.fe,0,1);return this};
g.h.isEmpty=function(){return 0==this.ub.length};g.B(KAa,x2);A2.prototype.ab=function(){return this.A};g.B(B2,g.ww);B2.prototype.C=null;B2.prototype.ak=function(){return this.Ye?g.pi(this.ra()):g.Da(this.width)&&g.Da(this.height)?new g.Qd(this.width,this.height):null};
B2.prototype.resume=function(){};g.B(LAa,t2);g.B(v2,GAa);g.B(u2,GAa);g.B(C2,HAa);C2.prototype.clear=function(){g.oe(this.ra())};
C2.prototype.setSize=function(a,b){F2(this.ra(),{width:a,height:b})};
g.B(MAa,KAa);g.B(D2,LAa);D2.prototype.setSize=function(a,b){F2(this.ra(),{width:a,height:b})};var H2;g.B(E2,B2);var OAa=0;g.h=E2.prototype;g.h.Lp=function(){var a=w2(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=w2(this,"g");this.H=w2(this,"defs");this.C=new C2(b,this);a.appendChild(this.H);a.appendChild(b);this.o=a;this.B&&(this.ra().setAttribute("preserveAspectRatio","none"),this.V?this.Yr():this.ra().setAttribute("viewBox","0 0 "+(this.B?this.B+" "+this.M:"")))};
g.h.Yr=function(){if(this.Ye){var a=this.ak();if(0==a.width)this.ra().style.visibility="hidden";else{this.ra().style.visibility="";var b=a.width/this.B;a=a.height/this.M;this.C.ra().setAttribute("transform","scale("+b+" "+a+") translate(0 0)")}}};
g.h.setSize=function(a,b){g.oi(this.ra(),a,b)};
g.h.ak=function(){if(!g.Zh)return this.Ye?g.pi(this.ra()):E2.fa.ak.call(this);var a=this.width,b=this.height,c=g.v(a)&&-1!=a.indexOf("%"),d=g.v(b)&&-1!=b.indexOf("%");if(!this.Ye&&(c||d))return null;if(c){var e=this.ra().parentNode;var f=g.pi(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ra().parentNode,f=f||g.pi(e),b=parseFloat(b)*f.height/100);return new g.Qd(a,b)};
g.h.clear=function(){this.C.clear();g.oe(this.H);this.A={}};
g.h.drawImage=function(a,b,c,d,e,f){a=w2(this,"image",{x:a,y:b,width:c,height:d,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",e);e=new D2(a,this);(f||this.C).ra().appendChild(e.ra());return e};
g.h.Sj=function(){var a=this.ak();E2.fa.Sj.call(this);a||this.dispatchEvent("resize");if(this.V){a=this.width;var b=this.height;"string"==typeof a&&-1!=a.indexOf("%")&&"string"==typeof b&&-1!=b.indexOf("%")&&this.K.X(PAa(),"tick",this.Yr);this.Yr()}};
g.h.om=function(){E2.fa.om.call(this);this.V&&this.K.Ka(PAa(),"tick",this.Yr)};
g.h.W=function(){delete this.A;delete this.H;delete this.C;this.K.dispose();delete this.K;E2.fa.W.call(this)};g.t(J2,g.mV);g.h=J2.prototype;
g.h.load=function(){g.mV.prototype.load.call(this);if(!K2(g.Y(this.player).playerStyle)){var a=g.Rna(this.player.getVideoData());if(a)a=I2(a,QAa(this)),L2(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",Gd:(0,g.A)(this.wR,this,a),ad:{v:a},withCredentials:!0};"gaming"==g.Y(this.player).playerStyle&&(a.ad.gaming="1");this.M&&(a.ad.ptype="embedded");var c=this.player.getVideoData().mB;c&&(a.Rb={ad_tracking:c});if(b=g.Qna(b))if(b=g.jd(b),b=g.gd(b))this.B=
g.eG(b,a)}}};
g.h.unload=function(){L2(this,null);this.B&&(this.B.abort(),this.B=null);g.mV.prototype.unload.call(this)};
g.h.Fc=function(a,b){if(!K2(g.Y(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=I2(b,"new");L2(this,c);return!0}return null};
g.h.getOptions=function(){return K2(g.Y(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.wR=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=I2(c,QAa(this)))}L2(this,c)};
g.h.mD=function(){if(this.A&&this.A.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<hDa.length;f++){var k=Math.abs(b.width-hDa[f]);if(-1==e||d>=k)e=f,d=k}d=iDa[e];this.C&&g.Xh(this.C.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.A.elements.length;++b)if(f=this.A.elements[b].id,e=this.o[f],k=this.G[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.oi(e.element,Math.round(k.width*a.width),f);g.di(e.element,m,n);g.Or(e.element,jDa);m=k.left+k.width/2;k=k.top+l/2;g.T(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Or(e.element,iDa);g.T(e.element,d);(e=g.Xd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Xh(e,"height",f+"px")}}}}};
g.h.MN=function(a){if(this.A)if("ytp-ce-in-endscreen"==a.getId())this.K=!1,this.A.skip&&1==this.player.getPlayerState()?(g.TU(this.player,!0),this.player.seekTo(Infinity),this.K=!0):(O2(this,this.A.impressionUrls),(a=g.FI())&&this.A.visualElement&&g.rI(a,this.A.visualElement));else if(!this.K){a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.T(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.T(b,"ytp-ce-shown");O2(this,c.impressionUrls);
(b=g.FI())&&g.rI(b,c.visualElement);g.Y(this.player).Nb&&this.player.Ba("endscreenelementshown",a)}};
g.h.NN=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.K){a=a.getId().substring(15);var b=this.o[a];g.Nr(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Nr(b,"ytp-ce-shown");g.Y(this.player).Nb&&this.player.Ba("endscreenelementhidden",a)}};
g.h.MU=function(a){var b=this;a.target===window&&(new g.V(function(){for(var c in b.o)g.Or(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.FE=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Lr(c,"ytp-ce-element");){g.Lr(c,"subscribe-label")&&P2(this,a);if(g.Lr(c,"ytp-ce-channel-subscribe"))return;c=g.ve(c)}if(!c||g.Lr(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Zw(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.Sr?(P2(this,a),this.UF(),this.player.pauseVideo(),c=g.jd(a.targetUrl),c=g.gd(c),g.uV(c,void 0,a.Id)):(c=this.player.getVideoData().Ic,
c=(0,g.A)(this.QV,this,c,a.targetUrl,a.Id),c=(0,g.A)(this.UF,this,c),P2(this,a,c))}}};
g.h.QV=function(a,b,c){var d=g.NF(b);a&&d&&(d.v||d.list)?g.M0(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.tV(b,c)};
g.h.mw=function(a,b){g.Lr(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.T(a.element,"ytp-ce-element-hover"):g.Y(this.player).A?(new g.V(function(){g.T(a.element,"ytp-ce-element-hover")},200)).start():g.T(a.element,"ytp-ce-element-hover"),O2(this,b.cM),N2(this,b.id,!0))};
g.h.Zw=function(a,b){g.Nr(a.element,"ytp-ce-element-hover");g.Nr(a.element,"ytp-ce-force-expand");N2(this,b.id,!1)};
g.h.UF=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var hDa=[346,426,470,506,570,640,853,1280,1920],iDa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),jDa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var bBa={gZ:"current",m1:"new"};var dBa={CLOSE:"close",r1:"openUrl",vJ:"subscribe"},eBa={Qs:"click",CLOSE:"close",y_:"hidden",q2:"rollOut",oJ:"rollOver",qJ:"shown"};var hBa={p4:"xx",q4:"xy",w4:"yx",x4:"yy"};g.t(nBa,b3);var tBa={WH:"anchored",c2:"rect",F2:"shapeless"};var yBa={CLOSED:"closed",C1:"playerControlShow",oJ:"rollOver",qJ:"shown"};d3.prototype.Xa=function(){var a=HBa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
d3.prototype.showLinkIcon=function(){return f3(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var e3={WH:"anchored",ZH:"branding",CHANNEL:"channel",fZ:"cta",B_:"highlightText",d0:"label",PLAYLIST:"playlist",O1:"popup",T2:"speech",vJ:"subscribe",t3:"title",VIDEO:"video",i4:"website"},DBa={ZH:"branding",CY:"card",JZ:"drawer",A_:"highlight",z0:"marker",U1:"promotion",TEXT:"text",m4:"widget"},EBa={Z3:"video_relative",D1:"player_relative"};NBa.prototype.B=function(a,b,c,d){this.o[a]=b?!c:c;a=g.Sb(this.o,function(e){return e});
this.C!=a&&(this.C=a,this.A.U(this.D,a,d))};i3.prototype.ra=function(){return this.D};
i3.prototype.C=function(){};var m3={bevel:1,dropshadow:2};g.t(o3,i3);
o3.prototype.C=function(a,b){var c=h3(a);if(c){var d=c3(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=KBa(a))&&c.o?c.o:null)&&c.length?c[0]:null){var f=g.Oh(jBa(b,kBa(e,new g.Lh(e.H,e.J,e.Al,e.C),b.o))),k=d.clone();c=new g.Lh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.A;k=n3(k,c.effects);l=j3(this,k.width,k.height);m=VBa(c,k.width,k.height,
this.o);d=new g.Lh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.Od(f.x-k.left,f.y-k.top);this.B=17*a3(b.o,e.A,e.o?e.o:"xy");e=c.cornerRadius;f=a.A;var p=this.o&&g3(a),q=p?f.borderWidth+1:f.borderWidth;p=(f=q?new A2(q,p?f.A:f.borderColor):null)?f.ab()/2:0;q=XBa(d,n);var u=this.F(d,e,n,q),w=n.x;n=n.y;var D=d.width,F=d.height,I=d.left;d=d.top;var O=new y2;O.moveTo(I+e+p,d+p);"t"==q&&(O.Hc(u.start,d+p),O.Hc(w,n),O.Hc(u.end,d+p));O.Hc(I+D-e-p,d+p);z2(O,e,e,-90);"r"==q&&(O.Hc(I+D-p,u.start),
O.Hc(w,n),O.Hc(I+D-p,u.end));O.Hc(I+D-p,d+F-e-p);z2(O,e,e,0);"b"==q&&(O.Hc(u.end,d+F-p),O.Hc(w,n),O.Hc(u.start,d+F-p));O.Hc(I+e+p,d+F-p);z2(O,e,e,90);"l"==q&&(O.Hc(I+p,u.end),O.Hc(w,n),O.Hc(I+p,u.start));O.Hc(I+p,d+e+p);z2(O,e,e,180);O.close();G2(l,O,f,m);if(m=this.ra())g.T(m,"annotation-shape"),g.T(m,"annotation-speech-shape"),g.di(m,k.left,k.top),g.oi(m,k.width,k.height),WBa(l,m,c.effects)}}}};
o3.prototype.F=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.Jd(k-f/2,l+b,l+m-f-b);return new j2(k,k+f)}
return"t"==d||"b"==d?e(this.B,c.x,a.left,a.width):"l"==d||"r"==d?e(this.B,c.y,a.top,a.height):new j2(0,0)};g.t(p3,i3);p3.prototype.C=function(a,b){var c=h3(a);if(c){var d=c3(c,b);if(!(0>=d.width||0>=d.height)){var e=a.A;c=n3(d,e.effects);var f=j3(this,c.width,c.height),k=new g.Lh(0,0,d.width,d.height),l=e.cornerRadius;d=new A2(!e.C&&this.o?1:e.C,e.bgColor);var m=new u2("#000",0),n=d?d.ab()/2+1:0;k=UBa(k,l,n);G2(f,k,d,m);f=this.ra();g.T(f,"annotation-shape");e=e.o;g.ri(f,this.o?Math.max(e,.9):e);g.di(f,c.left,c.top);g.oi(f,c.width,c.height)}}};g.t(q3,i3);
q3.prototype.C=function(a,b){var c=h3(a);if(c){var d=c3(c,b);if(!(0>=d.width||0>=d.height)){c=a.A;var e=n3(d,c.effects),f=j3(this,e.width,e.height),k=new g.Lh(0,0,d.width,d.height);d=VBa(c,d.width,d.height,this.o);var l=c.cornerRadius;var m=a.A;var n=this.o&&g3(a),p=n?m.borderWidth+1:m.borderWidth;n=(m=p?new A2(p,n?m.A:m.borderColor):null)?m.ab()/2+1:0;k=UBa(k,l,n);G2(f,k,m,d);if(k=this.ra())g.T(k,"annotation-shape"),g.T(k,"annotation-popup-shape"),g.di(k,e.left,e.top),g.oi(k,e.width,e.height),WBa(f,
k,c.effects)}}};g.t(r3,o3);r3.prototype.F=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new j2(k,k+f)}
return"t"==d||"b"==d?e(this.B,c.x,a.left,a.width):"l"==d||"r"==d?e(this.B,c.y,a.top,a.height):new j2(0,0)};g.t(s3,g.K);g.h=s3.prototype;g.h.vD=function(){this.J||(this.B&&g.M(this.B,!0),this.D&&g.M(this.D,!0),this.C&&(this.C.o=!0,g.ri(this.A,w3(this)?1:0),this.C.C(this.o,u3(this))),this.H.isActive()&&this.H.stop(),this.J=!0,this.K=this.Z.Oh(g.QU(this.F),"mouseleave",function(a){this.Oq.stop();this.Wh(a)}))};
g.h.Wh=function(){this.J&&(this.V?this.H.start():this.kC(),this.C&&(this.C.o=!1,g.ri(this.A,w3(this)?1:0),this.C.C(this.o,u3(this))),this.J=!1,this.K&&(this.Z.Ka(this.K),this.K=null))};
g.h.kC=function(){this.B&&g.M(this.B,!1);this.D&&g.M(this.D,!1)};
g.h.CO=function(a){this.ba=a;this.Oq.Jm()};
g.h.wL=function(){var a=this.ba,b=new g.Od(a.clientX,a.clientY),c=g.hi(this.F.getRootNode()),d=aCa(c,this.M);c=(this.D&&g.si(this.D)||this.B&&g.si(this.B))&&aCa(c,this.V);d&&d.contains(b)||c&&c.contains(b)?this.vD(a):this.Wh(a)};
g.h.show=function(){var a=this.o.A;a=(a&&0==a.o||"title"==this.o.style||"highlightText"==this.o.style?!1:!0)&&!this.C;var b=!this.A;if(a){var c=u3(this),d=null;"highlight"==this.o.type||"label"==this.o.style?d=new p3:"popup"==this.o.style?d=new q3:"anchored"==this.o.style?d=new o3:"speech"==this.o.style&&(d=new r3);d&&(d.C(this.o,c),this.C=d,c=d.ra())&&(g.M(c,!1),g.T(c,"annotation-type-"+this.o.type.toLowerCase()),this.Y(c))}if(b){c=["annotation"];"highlightText"!=this.o.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.o.type.toLowerCase());this.A=g.ie("DIV",c);g.M(this.A,!1);this.o.B&&(this.G=g.ie("DIV","inner-text"),"label"==this.o.style&&(g.T(this.G,"player-label-text"),this.G.style.backgroundColor=this.o.A.bgColor),g.ye(this.G,this.o.B),this.A.appendChild(this.G));g.nF(this.A,"annotation_id",this.o.id);this.Y(this.A);YBa(this,this.A);if(g3(this.o)&&this.o.showLinkIcon()){if(d=this.o.Xa())c=this.A,d=new g.Tn($2(d)),c.title=d.A+d.C;this.D=g.ie("SPAN","annotation-link-icon");g.M(this.D,
!1);this.A.appendChild(this.D)}ZBa(this);g3(this.o)||(this.A.style.cursor="default")}if(a||b){a:{a=this.o.segment.o;if(a.length&&(a=vBa(a[0]))){a=a.D;break a}a=0}this.A&&(this.A.style.zIndex=a);this.C&&this.C.ra()&&(this.C.ra().style.zIndex=a)}g.M(this.A,!0);g.ri(this.A,w3(this)?1:0);v3(this);this.C&&this.C.ra()&&g.M(this.C.ra(),!0)};
g.h.hide=function(){this.A&&g.M(this.A,!1);this.C&&this.C.ra()&&g.M(this.C.ra(),!1);this.L&&(this.Z.Ka(this.L),this.L=null)};g.t(x3,g.K);g.h=x3.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(cCa(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.A.subscribe("resize",this.uD,this),this.A.subscribe("onVideoAreaChange",this.kF,this))};
g.h.destroy=function(){if(this.view){cCa(this);var a=this.view;g.rH(a.Z);a.Oq.dispose();a.H.dispose();a.A&&g.qe(a.A);a.C&&a.C.ra()&&g.qe(a.C.ra())}y3(this)};
g.h.kF=function(){v3(this.view)};
g.h.uD=function(){v3(this.view)};g.t(dCa,s2);g.t(z3,s2);g.t(eCa,z3);g.t(fCa,s2);g.t(gCa,s2);g.t(iCa,z3);g.t(jCa,z3);g.t(kCa,s2);g.t(A3,s2);J3.prototype.C=function(a,b){var c=g.Ee(b.target,"label");c&&g.U(c,"iv-card-poll-choice-focused",a)};
J3.prototype.G=function(a,b){var c=g.Fe(b.target,"iv-card-poll");if(c)if(a.B)g.Zd("iv-card-sign-in-button",c).click();else{var d=parseInt(wAa(b.target),10);if(null==a.o)a.choices[d].count++,a.o=d;else if(a.o!=d){var e=a.choices[a.o];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.o=d}else e=a.choices[a.o],e.count=Math.max(e.count-1,0),a.o=null;pCa(a,c);g.iG(this.o.videoData.re,{ad:{action_poll_vote:1},Rb:{poll_id:a.id,index:d,session_token:a.J}});F3(this.o.logger,a.C,void 0,{"link-id":d},a.A.click,
5);(c=g.FI())&&g.sI(c,a.F)}};
J3.prototype.F=function(a){var b=g.y("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.J,a.G)});
tCa(this,a,!0,c)};
J3.prototype.H=function(a){var b=g.y("yt.www.ypc.bootstrap.api.loadOffers");b&&(b=g.Na(b,a.M,a.J,a.G));tCa(this,a,!1,b)};g.t(S3,g.K);g.h=S3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.mR(a,b,{id:c});g.L(this,a);a.namespace="annotations_module";d&&rAa(a).subscribe("onEnter",d,this);e&&rAa(a).subscribe("onExit",e,this);g.ZU(this.context.o,[a])};
g.h.Kr=function(){this.context.C.subscribe("resize",this.To,this)};
g.h.ra=function(){return this.Fa};
g.h.ll=function(a,b,c,d,e,f,k){this.context.A.X(a,"click",g.Na(this.lq,b,c,d,e,f||[],k||0),this);this.context.A.X(a,"touchstart",g.Na(function(){this.Ky=!1}),this);
this.context.A.X(a,"touchmove",g.Na(function(){this.Ky=!0}),this)};
g.h.lq=function(a,b,c,d,e,f,k){if(this.Ky)return!1;k&&(k.stopPropagation(),k.preventDefault());BCa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.ea=(0,g.H)()};
g.h.hide=function(){};
g.h.destroy=function(){g.qe(this.ra())};
g.h.To=function(){};g.t(V3,S3);g.h=V3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.C.length)(a=this.A.getRootNode())?(a=g.pi(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.To=function(){var a=this.isAvailable();g.M(this.ra(),a);g.U(this.context.o.getRootNode(),"ytp-iv-drawer-enabled",a);i2(this.A)};
g.h.destroy=function(){this.A.il(!1);this.A.getRootNode().removeChild(this.G);g.yF(this.L);g.gH(this.ba);this.ga&&this.ga.dispose();this.H&&this.H.dispose();S3.prototype.destroy.call(this)};
g.h.eO=function(a){this.V.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.cG=function(a){if(!g.Lr(this.A.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.FI(),c=this.o?this.o.jc.D:this.K;b&&c&&r2(b,[c]);this.o=a;W3(this)}g.si(this.ra())&&(2==this.context.o.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.o.getAdState():void 0):(b=isNaN(void 0)?this.context.o.getPlayerState():void 0,b=1==b||0==b&&0===this.context.o.getCurrentTime()),b&&a.jc.teaserDurationMs&&this.A.il(!0,{teaserText:a.jc.teaserText,durationMs:a.jc.teaserDurationMs}));this.ma.isActive()||
((!this.D||!this.V.isActive()&&this.aa)&&LCa(this,a),this.ma.start(910+a.jc.teaserDurationMs))}};
g.h.HV=function(a){this.D||(this.o=a,W3(this),LCa(this,a),T3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.lK=function(){if(this.D){H3(this.context.logger,this.Y,4,X3(this).A.close);var a=g.FI();a&&this.M&&g.sI(a,this.M);U3(this)}};
g.h.xK=function(){g.U(this.G,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.lN=function(){var a=g.FI(),b=X3(this);b=b?b.D:this.K;a&&b&&q2(a,[b])};
g.h.kN=function(){var a=g.FI(),b=X3(this);b=b?b.D:this.K;a&&b&&r2(a,[b])};
g.h.oN=function(){var a=X3(this);I3(this.context.logger,8,a.C,a.A.ZV);var b=g.FI();b&&a&&q2(b,[a.H,a.D])};
g.h.nN=function(){var a=g.FI(),b=X3(this);a&&b&&r2(a,[b.H])};
g.h.mN=function(a){var b=X3(this),c=g.FI();this.o?a?(a=this.context.logger,I3(a,9,b.C,b.A.ey),a.o.sendVideoStatsEngageEvent(4,void 0),c&&g.sI(c,b.H)):(a=this.context.logger,I3(a,12,b.C,b.A.ey),a.o.sendVideoStatsEngageEvent(4,void 0),c&&g.sI(c,b.D)):(a=this.context.logger,H3(a,this.Y,12,b.A.ey),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.K&&g.sI(c,this.K))};
var CCa={collaborator:dCa,donation:eCa,episode:A3,movie:A3,playlist:fCa,poll:gCa,productListing:iCa,simple:z3,tip:jCa,video:kCa};g.t(Y3,S3);Y3.prototype.Kr=function(){S3.prototype.Kr.call(this);MCa(this)};
Y3.prototype.show=function(){S3.prototype.show.call(this);var a=g.FI(),b=this.annotation.data;a&&b&&(b=b.session_data)&&q2(a,[g.oI(b.itct)])};
Y3.prototype.hide=function(){S3.prototype.hide.call(this);var a=g.FI(),b=this.annotation.data;a&&b&&(b=b.session_data)&&r2(a,[g.oI(b.itct)])};g.t(Z3,Y3);g.h=Z3.prototype;g.h.RV=function(a,b,c,d){this.C.stop();if(!this.B){var e=g.pi(a);this.o||(g.ni(a,e.width),g.ni(b,e.width));g.Xh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.Xh(c,"right","1px");this.B=!0;g.M(a,!0);this.D=new g.V(function(){g.T(this.ra(),"iv-branding-active")},0,this);
this.D.start()}};
g.h.aM=function(a,b){g.Nr(this.ra(),"iv-branding-active");this.F=new g.V((0,g.A)(function(){g.M(a,!1);this.o||g.ni(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){Y3.prototype.show.call(this);if(!this.G){g.T(this.ra(),"iv-branding");var a=this.annotation.data;this.H=a.image_width;this.A=g.ie("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.M(this.A,!1);var b=g.ie("DIV","branding-img-container",this.A);this.ra().appendChild(b);var c=g.ie("DIV","iv-branding-context-name");g.ye(c,a.channel_name);var d=g.ie("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=
new g.y_(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.o),this.o.A(d);b=g.ie("DIV","iv-branding-context-subscribe-caret");c=g.ie("DIV","branding-context-container-inner",b,c,d);g.M(c,!1);d=g.ie("DIV","branding-context-container-outer",c);g.Xh(d,"right",this.H+"px");this.ra().appendChild(d);var e=this.annotation.Xa();e&&this.ll(this.A,e,this.annotation.id,a.session_data,
this.annotation.o);this.C=new g.V(g.Na(this.aM,c,d),500,this);g.L(this,this.C);this.context.A.X(this.ra(),"mouseover",(0,g.A)(this.RV,this,c,d,b,a.image_height));this.context.A.X(this.ra(),"mouseout",(0,g.A)(this.C.start,this.C,void 0));this.G=!0}E3(this.context.logger,this.annotation.o);g.M(this.ra(),!0);this.isActive=!0;if(this.A){a=this.A;var f=void 0===f?0:f;b=g.qi(a).width;c=g.Da(void 0)?void 0:b;g.di(a,c);f=new p2(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,CAa);g.L(this,f);this.context.B.X(f,
"begin",g.Na(g.M,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(Y3.prototype.hide.call(this),g.M(this.ra(),!1),this.isActive=!1)};
g.h.destroy=function(){this.o&&(this.o.dispose(),this.o=null);Y3.prototype.destroy.call(this)};g.t($3,Y3);g.h=$3.prototype;g.h.show=function(){this.isActive||(Y3.prototype.show.call(this),this.K||(NCa(this),this.K=!0),g.M(this.ra(),!0),this.annotation&&this.annotation.o&&E3(this.context.logger,this.annotation.o),g.ch(function(){g.Nr(this.ra(),"iv-promo-inactive")},100,this),this.ra().removeAttribute("aria-hidden"),this.isActive=!0,a4(this),PCa(this),QCa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.T(this.ra(),"iv-promo-inactive"),this.isActive=!1,this.ra().setAttribute("aria-hidden",!0))};
g.h.lq=function(a,b,c,d,e,f,k){return this.D?!1:Y3.prototype.lq.call(this,a,b,c,d,e,f,k)};
g.h.Ru=function(a,b){b.stopPropagation();PCa(this);QCa(this,a);this.o.focus()};
g.h.yL=function(a){this.J=!0;this.Ru(500,a)};
g.h.xL=function(){this.J=!1;OCa(this)};
g.h.DO=function(a){a.stopPropagation();this.hide();G3(this.context.logger,this.annotation.o)};
g.h.nL=function(a){a.stopPropagation();a4(this);this.D=!0;g.T(this.ra(),"iv-promo-collapsed-no-delay");this.F.start();G3(this.context.logger,this.annotation.o)};
g.h.destroy=function(){this.F.dispose();Y3.prototype.destroy.call(this)};g.t(b4,g.mV);g.h=b4.prototype;g.h.Fc=function(a,b){if(!SCa(g.Y(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.xt(b);c&&d4(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(ECa(this.o,b),i2(this.player)),!0}return null};
g.h.getOptions=function(){return SCa(g.Y(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.ax=function(){if(this.B){var a=g.QU(this.player).getVideoContentRect(!0);g.oi(this.B.element,a.width,a.height);g.di(this.B.element,a.left,a.top)}if(this.o){var b=g.XU(this.player);a=this.o;b=b.width;g.U(a.G,"iv-drawer-small",426>=b);g.U(a.G,"iv-drawer-big",1280<=b)}};
g.h.XS=function(a){this.Nc(a.state);g.X(a.state,2)&&(this.ce()&&this.se()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.il(!1))};
g.h.load=function(){g.mV.prototype.load.call(this);this.Nc(g.PU(this.player));this.J++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.A)(this.AR,this,b,this.J),d=(0,g.A)(function(){this.F=null},this);
g.ZH()&&(c=ZCa(this,c));c={format:"XML",Gd:c,onError:d,ad:{}};a.isPharma&&(c.ad.pharma="1");c.method="POST";c.withCredentials=!0;d=g.Y(this.player);"gaming"==d.playerStyle&&(c.ad.gaming="1");(b=d.J.get(b))&&$Ca(c,b);b=b&&(b.ri||b.St);if(!a.Mo||b)a.re?TCa(this,a.re,c):(this.C=(0,g.A)(this.LN,this,c),this.player.addEventListener("videodatachange",this.C));g.dV(this.player,this.B.element,4);this.ax()};
g.h.Nc=function(a){a=!a.isCued()&&!g.X(a,1024);g.lQ(this.D,a);g.lQ(this.B,a)};
g.h.LN=function(a){var b=this.player.getVideoData();b.re&&(this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null),TCa(this,b.re,a))};
g.h.unload=function(){mCa(this.jb);g.bV(this.player,"annotations_module");g.Nb(this.A,function(a){a.destroy()});
g.Nb(this.L,function(a){a.destroy()});
this.H=null;this.o&&(this.o.destroy(),this.o=null,i2(this.player));this.K=!1;this.F&&(this.F.abort(),this.F=null);this.A={};this.L={};this.D.hide();g.mV.prototype.unload.call(this);g.kQ(this.B);this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null)};
g.h.AR=function(a,b,c){this.F=null;if(!VCa(this,b,a)&&(a=g.ZF(c)&&c.responseXML?c.responseXML:null)){d4(this,a);g.T(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.A){b=this.A[d].annotation;if(b.segment)if(c=b.segment,c.o.length)if(c=c.o[0].A||c.o[0].o||c.o[0].C,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.B,f.visible=!0);b=new g.mR(c,e,f);a.push(b)}}g.ZU(this.player,a)}};
g.h.jF=function(a){a==this.player.getVideoData().videoId&&(this.loaded?aDa(this):this.load())};
g.h.IN=function(a){a=a.getId();var b=this.A[a];b&&!b.C&&(b=b.annotation,dDa(this,a),E3(this.jb,b.o))};
g.h.JN=function(a){e4(this,a.getId())};
g.h.jC=function(a){a&&(a.hide(),f4(this,"shown",!1,a.annotation.id),this.pp(a.annotation,"hidden"))};
g.h.oG=function(a){a&&(a.show(),f4(this,"shown",!0,a.annotation.id),this.pp(a.annotation,"shown"))};
g.h.sU=function(a,b,c){var d=this.A[a];if(d&&b.value!=c){b.value=c;var e=!1;IBa(d.annotation,function(f){e=e||f.value});
eDa(this,a,b,e)}};
g.h.sQ=function(a){if(a&&a.id){var b=a.Xa();if(b){var c=$2(b);if(c){var d=(0,g.A)(this.pp,this,a,"click");if("new"==R3(c,b.target)||fDa(this,b))d(),d=null;F3(this.jb,a.o,d)}}}};
g.h.pp=function(a,b){GBa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!fDa(this,c.url))){e=yCa(c.url);var f=xCa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=c4(this).o,g.M0(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&c4(this).o.Jc()&&c4(this).o.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.Y(this.player),(d=$2(c.url))?(f=wCa(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Na(zCa,e.pageId,e.Oc),d=new g.Tn(d),g.Xn(d,e(d.C)),d=d.toString())):
d=null,d&&(this.player.pauseVideo(),c=R3(d,c.url.target),e=a.itct,"ei"in g.NF(d)&&(d=g.Dh(d,"ei")),g.uV(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.JR=function(){f4(this,"playerControlShow",!1)};
g.h.RT=function(){f4(this,"playerControlShow",!0)};
g.h.KN=function(a){f4(this,"rollOver",!0,a.id)};
g.h.Wh=function(a){f4(this,"rollOver",!1,a.id)};
g.h.YQ=function(a){a&&a.id&&(this.A[a.id].C=!0,e4(this,a.id),G3(this.jb,a.o),this.pp(a,"close"),f4(this,"closed",!0,a.id))};
g.h.ce=function(){return!!this.o&&this.o.isAvailable()};
g.h.se=function(){this.ce();return!!this.o&&this.o.D};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ce();this.o&&(a?c?T3(this.o,c,b):T3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):U3(this.o))};
g.h.il=function(a,b){this.player.U(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.W=function(){g.Y(this.player).J.unsubscribe("vast_info_card_add",this.jF,this);g.Nr(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.$H(a[b]);this.M.length=0;g.mV.prototype.W.call(this)};g.WZ.annotations_module=b4;g.WZ.creatorendscreen=J2;})(_yt_player);
